const slides=[...document.querySelectorAll('.slide')], dots=[...document.querySelectorAll('.pagination button')];let current=0,timer;
function show(n){current=(n+slides.length)%slides.length;slides.forEach((s,i)=>s.classList.toggle('active',i===current));dots.forEach((d,i)=>d.classList.toggle('active',i===current));restart()}
function restart(){clearInterval(timer);timer=setInterval(()=>show(current+1),6500)}
document.querySelector('.next').onclick=()=>show(current+1);document.querySelector('.prev').onclick=()=>show(current-1);dots.forEach(d=>d.onclick=()=>show(+d.dataset.go));
const hero=document.querySelector('.hero');hero.addEventListener('mouseenter',()=>clearInterval(timer));hero.addEventListener('mouseleave',restart);let sx=0;hero.addEventListener('touchstart',e=>sx=e.touches[0].clientX,{passive:true});hero.addEventListener('touchend',e=>{const dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>45)show(current+(dx<0?1:-1))},{passive:true});
const translations={
en:{navHome:'Home',navAbout:'About',navServices:'Services',navCourses:'Courses',navContact:'Contact',eyebrow1:'DORO SOLUTIONS',hero1:'Solutions That<br>Move You Forward.',hero1p:'Professional support for your business, finances and next steps.',contactUs:'Contact Us',eyebrow2:'TAX SERVICES',hero2:'Tax Season<br>Is Coming.',hero2p:'Start getting organized now and be ready for a smoother tax season.',getPrepared:'Get Prepared',eyebrow3:'LEARN & GROW',hero3:'Our Courses.',hero3p:'Learn, grow and build new opportunities with practical learning.',exploreCourses:'Explore Courses',whatWeDo:'WHAT WE DO',ourServices:'Our Services',taxPrep:'Tax Preparation',bookkeeping:'Bookkeeping',admin:'Administrative Support',notary:'Notary Public',viewServices:'View All Services <span>→</span>',learnGrow:'LEARN & GROW',ourCourses:'Our Courses',courseTag:'Learn, Grow and Build New Opportunities.',courseDesc:'Practical courses designed to give you the knowledge and skills to move forward with confidence.',exploreCourses2:'Explore Courses <span>→</span>',letsConnect:"LET'S CONNECT",spanish:'Hablamos Español',help:'Estamos aquí para ayudarte.',emailUs:'Email Us',schedule:'Schedule an Appointment',ready:'We’re ready to help.'},
es:{navHome:'Inicio',navAbout:'Nosotros',navServices:'Servicios',navCourses:'Cursos',navContact:'Contacto',eyebrow1:'DORO SOLUTIONS',hero1:'Soluciones que te<br>ayudan a avanzar.',hero1p:'Apoyo profesional para tu negocio, tus finanzas y tus próximos pasos.',contactUs:'Contáctanos',eyebrow2:'SERVICIOS DE IMPUESTOS',hero2:'La temporada de<br>impuestos se acerca.',hero2p:'Comienza a organizarte desde ahora y prepárate para una temporada de impuestos más sencilla.',getPrepared:'Prepárate',eyebrow3:'APRENDE Y CRECE',hero3:'Nuestros Cursos.',hero3p:'Aprende, crece y crea nuevas oportunidades con aprendizaje práctico.',exploreCourses:'Explorar Cursos',whatWeDo:'LO QUE HACEMOS',ourServices:'Nuestros Servicios',taxPrep:'Preparación de Impuestos',bookkeeping:'Bookkeeping',admin:'Apoyo Administrativo',notary:'Notaría Pública',viewServices:'Ver Todos los Servicios <span>→</span>',learnGrow:'APRENDE Y CRECE',ourCourses:'Nuestros Cursos',courseTag:'Aprende, Crece y Crea Nuevas Oportunidades.',courseDesc:'Cursos prácticos diseñados para brindarte conocimientos y habilidades para avanzar con confianza.',exploreCourses2:'Explorar Cursos <span>→</span>',letsConnect:'HABLEMOS',spanish:'Hablamos Español',help:'Estamos aquí para ayudarte.',emailUs:'Envíanos un email',schedule:'Agenda una cita',ready:'Estamos listos para ayudarte.'}};
function setLang(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const v=translations[lang][el.dataset.i18n];if(v!==undefined)el.innerHTML=v});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('doro-lang',lang)}
document.querySelectorAll('[data-lang]').forEach(b=>b.onclick=()=>setLang(b.dataset.lang));setLang(localStorage.getItem('doro-lang')||'en');
const mt=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav');mt.onclick=()=>{const open=nav.classList.toggle('open');mt.setAttribute('aria-expanded',open)};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));restart();
