const T={
en:{home:"Home",services:"Services",courses:"Courses",about:"About",contact:"Contact",s1a:"Solutions That",s1b:"Move You Forward.",s1p:"Professional services and practical education<br>to help you achieve your goals.",s1btn:"Contact Us",s2a:"Tax Season",s2b:"Is Coming.",s2p:"Get professional tax preparation and support<br>you can trust.",s2btn:"Learn More",s3a:"Our",s3b:"Courses.",s3p:"Learn, grow and build new opportunities.",s3btn:"Explore Courses",ourServices:"Our Services",taxPrep:"Tax<br>Preparation",bookkeeping:"Bookkeeping",admin:"Administrative<br>Support",notary:"Notary Public",viewServices:"View All Services",ourCourses:"Our Courses",courseTitle:"Learn, Grow and<br>Build New Opportunities.",courseP:"Practical courses designed to give you the knowledge<br>and skills to move forward with confidence.",explore:"Explore Courses",contactUs:"Contact Us",speakSpanish:"We Speak Spanish",hereHelp:"We're here to help.",sendEmail:"Send us an email",appointment:"Schedule an appointment",ready:"We're ready to help."},
es:{home:"Inicio",services:"Servicios",courses:"Cursos",about:"Nosotros",contact:"Contacto",s1a:"Soluciones Que",s1b:"Te Impulsan.",s1p:"Servicios profesionales y educación práctica<br>para ayudarte a alcanzar tus metas.",s1btn:"Contáctanos",s2a:"La Temporada de Impuestos",s2b:"Se Acerca.",s2p:"Preparación profesional de impuestos y el apoyo<br>en el que puedes confiar.",s2btn:"Conoce Más",s3a:"Nuestros",s3b:"Cursos.",s3p:"Aprende, crece y crea nuevas oportunidades.",s3btn:"Explorar Cursos",ourServices:"Nuestros Servicios",taxPrep:"Preparación de<br>Impuestos",bookkeeping:"Contabilidad",admin:"Apoyo<br>Administrativo",notary:"Notaría Pública",viewServices:"Ver Servicios",ourCourses:"Nuestros Cursos",courseTitle:"Aprende, Crece y<br>Crea Nuevas Oportunidades.",courseP:"Cursos prácticos diseñados para darte el conocimiento<br>y las habilidades para avanzar con confianza.",explore:"Explorar Cursos",contactUs:"Contáctanos",speakSpanish:"Hablamos Español",hereHelp:"Estamos aquí para ayudarte.",sendEmail:"Envíanos un email",appointment:"Agenda una cita",ready:"Estamos listos para ayudarte."}
};
const slides=[...document.querySelectorAll(".slide")],dots=[...document.querySelectorAll(".dots button")];let cur=0,timer;
function show(n){cur=(n+3)%3;slides.forEach((s,i)=>s.classList.toggle("active",i===cur));dots.forEach((d,i)=>d.classList.toggle("active",i===cur))}
function auto(){clearInterval(timer);timer=setInterval(()=>show(cur+1),6500)}
document.querySelector(".next").onclick=()=>{show(cur+1);auto()};document.querySelector(".prev").onclick=()=>{show(cur-1);auto()};dots.forEach((d,i)=>d.onclick=()=>{show(i);auto()});auto();
document.querySelectorAll(".lang button").forEach(b=>b.onclick=()=>{let l=b.dataset.lang;document.documentElement.lang=l;document.querySelectorAll("[data-i]").forEach(el=>el.innerHTML=T[l][el.dataset.i]);document.querySelectorAll(".lang button").forEach(x=>x.classList.toggle("active",x===b));});
document.querySelector(".menu").onclick=()=>document.querySelector(".nav-shell").classList.toggle("open");